/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32g431xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//led(1,2,3,4) - PB(3,4,5,6)
//button(1,2,3) - PC(13,14,15)
//button - PC13
int main(void)
{
	RCC->AHB2ENR |= (RCC_AHB2ENR_GPIOBEN) | (RCC_AHB2ENR_GPIOCEN);

	GPIOB->MODER &= ~(GPIO_MODER_MODE3_Msk | GPIO_MODER_MODE4_Msk | GPIO_MODER_MODE5_Msk | GPIO_MODER_MODE6_Msk);
	GPIOC->MODER &= ~(GPIO_MODER_MODE13_Msk | GPIO_MODER_MODE14_Msk | GPIO_MODER_MODE15_Msk);
	GPIOB->MODER |= (1 << GPIO_MODER_MODE3_Pos) | (1 << GPIO_MODER_MODE4_Pos) | (1 << GPIO_MODER_MODE5_Pos) | (1 << GPIO_MODER_MODE6_Pos);
	GPIOC->MODER |= (0 << GPIO_MODER_MODE13_Pos) | (0 << GPIO_MODER_MODE14_Pos) | (0 << GPIO_MODER_MODE15_Pos);
	GPIOC->ODR |= GPIO_ODR_OD13 | GPIO_ODR_OD14 | GPIO_ODR_OD15;
	while(1)
	{
		if((GPIOC->IDR & GPIO_IDR_ID13) == 0)
		{
			GPIOB->ODR |= GPIO_ODR_OD3;
		}

		else if((GPIOC->IDR & GPIO_IDR_ID13))
		{
			GPIOB->ODR &= ~GPIO_ODR_OD3;
		}

		if((GPIOC->IDR & GPIO_IDR_ID14) == 0)
		{
			GPIOB->ODR |= GPIO_ODR_OD4;
		}

		else if(GPIOC->IDR & GPIO_IDR_ID14)
		{
			GPIOB->ODR &= ~GPIO_ODR_OD4;
		}

		if((GPIOC->IDR & GPIO_IDR_ID15) == 0)
		{
			GPIOB->ODR |= GPIO_ODR_OD5;
		}

		else if(GPIOC->IDR & GPIO_IDR_ID15)
		{
			GPIOB->ODR &= ~GPIO_ODR_OD5;
		}

	}
}
